import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="h-screen w-screen flex items-center justify-center">
      <Head>
        <title>Microgen Function Extra - FrontEnd</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-2xl font-medium text-center">
        Microgen Function Extra - FrontEnd
      </h1>
    </div>
  );
};

export default Home;
